// ═══════════════════════════════════════════════════════════════
// getabuff — данные предметов и баффов
// Языки: ru, en, es, fr, zh, hi, ar (следующие по числу носителей).
// Каждый бафф — реальная полезная привычка в RPG-обёртке.
// Строки в двойных кавычках; апострофы — ’, выделение — «».
// ═══════════════════════════════════════════════════════════════

export const UI = {
  ru: {
    titleBefore: "Хочешь почувствовать себя ",
    titleEm: "лучше",
    titleAfter: "?",
    roll: "Получи бафф",
    claimed: "Бафф на сегодня получен",
    share: "Поделиться баффом",
    copied: "Ссылка скопирована",
    showMine: "Показать мой бафф",
    sharedNote: "этим баффом поделились с тобой",
    shareText: "Мой бафф на сегодня — «{item}»: {buff}",
    footer: "один бафф в день, эффект до полуночи",
    metaDesc: "Хочешь почувствовать себя лучше? Один бафф в день — случайный предмет и бонус к реальной жизни.",
    tiers: { common: "Обычный", rare: "Редкий", epic: "Эпический", legendary: "Легендарный" },
  },
  en: {
    titleBefore: "Want to feel ",
    titleEm: "better",
    titleAfter: "?",
    roll: "Get a buff",
    claimed: "Today’s buff is claimed",
    share: "Share the buff",
    copied: "Link copied",
    showMine: "Show my buff",
    sharedNote: "a buff someone shared with you",
    shareText: "My buff for today — «{item}»: {buff}",
    footer: "one buff a day, effect lasts until midnight",
    metaDesc: "Want to feel better? One buff a day — a random item and a bonus to real life.",
    tiers: { common: "Common", rare: "Rare", epic: "Epic", legendary: "Legendary" },
  },
  es: {
    titleBefore: "¿Quieres sentirte ",
    titleEm: "mejor",
    titleAfter: "?",
    roll: "Consigue un buff",
    claimed: "Ya tienes tu buff de hoy",
    share: "Compartir el buff",
    copied: "Enlace copiado",
    showMine: "Ver mi buff",
    sharedNote: "un buff que alguien ha compartido contigo",
    shareText: "Mi buff de hoy — «{item}»: {buff}",
    footer: "un buff al día, el efecto dura hasta medianoche",
    metaDesc: "¿Quieres sentirte mejor? Un buff al día: un objeto al azar y un bonus para la vida real.",
    tiers: { common: "Común", rare: "Raro", epic: "Épico", legendary: "Legendario" },
  },
  fr: {
    titleBefore: "Envie de te sentir ",
    titleEm: "mieux",
    titleAfter: " ?",
    roll: "Obtiens un buff",
    claimed: "Ton buff du jour est pris",
    share: "Partager le buff",
    copied: "Lien copié",
    showMine: "Voir mon buff",
    sharedNote: "un buff que quelqu’un a partagé avec toi",
    shareText: "Mon buff du jour — «{item}» : {buff}",
    footer: "un buff par jour, effet valable jusqu’à minuit",
    metaDesc: "Envie de te sentir mieux ? Un buff par jour : un objet aléatoire et un bonus pour la vraie vie.",
    tiers: { common: "Commun", rare: "Rare", epic: "Épique", legendary: "Légendaire" },
  },
  zh: {
    titleBefore: "想让自己感觉",
    titleEm: "更好",
    titleAfter: "吗？",
    roll: "获取增益",
    claimed: "今日增益已领取",
    share: "分享这个增益",
    copied: "链接已复制",
    showMine: "查看我的增益",
    sharedNote: "有人分享给你的增益",
    shareText: "我今天的增益 —— 「{item}」：{buff}",
    footer: "每天一个增益，效果持续到午夜",
    metaDesc: "想让自己感觉更好吗？每天一个增益：随机物品加一条现实生活加成。",
    tiers: { common: "普通", rare: "稀有", epic: "史诗", legendary: "传说" },
  },
  hi: {
    titleBefore: "क्या आप ",
    titleEm: "बेहतर",
    titleAfter: " महसूस करना चाहते हैं?",
    roll: "बफ़ पाएं",
    claimed: "आज का बफ़ मिल चुका है",
    share: "बफ़ शेयर करें",
    copied: "लिंक कॉपी हो गया",
    showMine: "मेरा बफ़ दिखाएं",
    sharedNote: "किसी ने आपके साथ यह बफ़ शेयर किया है",
    shareText: "आज मेरा बफ़ — «{item}»: {buff}",
    footer: "दिन में एक बफ़, असर आधी रात तक",
    metaDesc: "बेहतर महसूस करना चाहते हैं? दिन में एक बफ़ — एक रैंडम चीज़ और असल ज़िंदगी के लिए बोनस।",
    tiers: { common: "सामान्य", rare: "दुर्लभ", epic: "महाकाव्य", legendary: "पौराणिक" },
  },
  ar: {
    titleBefore: "هل تريد أن تشعر ",
    titleEm: "بتحسّن",
    titleAfter: "؟",
    roll: "احصل على تعزيز",
    claimed: "تم استلام تعزيز اليوم",
    share: "شارِك التعزيز",
    copied: "تم نسخ الرابط",
    showMine: "اعرض تعزيزي",
    sharedNote: "تعزيز شاركه معك أحدهم",
    shareText: "تعزيزي لهذا اليوم — «{item}»: {buff}",
    footer: "تعزيز واحد كل يوم، المفعول حتى منتصف الليل",
    metaDesc: "هل تريد أن تشعر بتحسّن؟ تعزيز واحد كل يوم: غرض عشوائي ومكافأة لحياتك الواقعية.",
    tiers: { common: "عادي", rare: "نادر", epic: "ملحمي", legendary: "أسطوري" },
  },
};

export const BUFFS = [
  // ── common ──────────────────────────────────────────────────
  {
    rarity: "common",
    ru: { item: "Стакан воды", buff: "+15 к бодрости, снят дебафф «Сушняк»", flavor: "Выпей прямо сейчас. Серьёзно." },
    en: { item: "Glass of water", buff: "+15 Alertness, «Cottonmouth» debuff removed", flavor: "Drink one right now. Seriously." },
    es: { item: "Vaso de agua", buff: "+15 de vigor, penalización «boca seca» eliminada", flavor: "Bébete uno ahora mismo. En serio." },
    fr: { item: "Verre d’eau", buff: "+15 en vivacité, malus «bouche sèche» retiré", flavor: "Bois-en un tout de suite. Sérieusement." },
    zh: { item: "一杯水", buff: "+15 清醒，移除「口干」减益", flavor: "现在就喝一杯。认真的。" },
    hi: { item: "एक गिलास पानी", buff: "+15 स्फूर्ति, «मुँह सूखना» डीबफ़ हटा", flavor: "अभी एक गिलास पिएं। सच में।" },
    ar: { item: "كوب ماء", buff: "+15 لليقظة، إزالة تأثير «جفاف الفم»", flavor: "اشرب كوبًا الآن. بجدية." },
  },
  {
    rarity: "common",
    ru: { item: "Пешая прогулка на 10 минут", buff: "+20 к ясности мышления", flavor: "Работает лучше, чем пятая чашка кофе." },
    en: { item: "A 10-minute walk", buff: "+20 Mental Clarity", flavor: "Beats a fifth cup of coffee." },
    es: { item: "Un paseo de 10 minutos", buff: "+20 de claridad mental", flavor: "Mejor que un quinto café." },
    fr: { item: "Une marche de 10 minutes", buff: "+20 en clarté d’esprit", flavor: "Mieux qu’un cinquième café." },
    zh: { item: "十分钟散步", buff: "+20 思维清晰", flavor: "比第五杯咖啡管用。" },
    hi: { item: "10 मिनट की सैर", buff: "+20 मानसिक स्पष्टता", flavor: "पाँचवीं कॉफ़ी से बेहतर।" },
    ar: { item: "مشي عشر دقائق", buff: "+20 لصفاء الذهن", flavor: "أفضل من فنجان القهوة الخامس." },
  },
  {
    rarity: "common",
    ru: { item: "Открытое окно", buff: "+12 к концентрации, −30% к сонливости", flavor: "Мозгу нужен кислород, а не героизм." },
    en: { item: "An open window", buff: "+12 Focus, −30% Drowsiness", flavor: "Your brain wants oxygen, not heroics." },
    es: { item: "Una ventana abierta", buff: "+12 de concentración, −30% de somnolencia", flavor: "Tu cerebro quiere oxígeno, no heroísmos." },
    fr: { item: "Une fenêtre ouverte", buff: "+12 en concentration, −30 % de somnolence", flavor: "Ton cerveau veut de l’oxygène, pas de l’héroïsme." },
    zh: { item: "开一扇窗", buff: "+12 专注，−30% 困倦", flavor: "大脑要的是氧气，不是硬撑。" },
    hi: { item: "एक खुली खिड़की", buff: "+12 फ़ोकस, −30% सुस्ती", flavor: "दिमाग़ को ऑक्सीजन चाहिए, वीरता नहीं।" },
    ar: { item: "نافذة مفتوحة", buff: "+12 للتركيز، −30% للنعاس", flavor: "دماغك يريد أكسجين، لا بطولات." },
  },
  {
    rarity: "common",
    ru: { item: "Заправленная кровать", buff: "+10 к самоуважению на весь день", flavor: "Одна победа до завтрака уже случилась." },
    en: { item: "A made bed", buff: "+10 Self-respect for the whole day", flavor: "One win before breakfast, already done." },
    es: { item: "La cama hecha", buff: "+10 de autoestima durante todo el día", flavor: "Una victoria antes del desayuno, ya conseguida." },
    fr: { item: "Un lit fait", buff: "+10 en amour-propre pour toute la journée", flavor: "Une victoire avant le petit-déj, déjà acquise." },
    zh: { item: "整理好的床", buff: "+10 自尊，持续一整天", flavor: "早饭前就赢了一场。" },
    hi: { item: "बिस्तर लगा हुआ", buff: "+10 आत्म-सम्मान, पूरे दिन के लिए", flavor: "नाश्ते से पहले एक जीत, हो गई।" },
    ar: { item: "سرير مرتّب", buff: "+10 لاحترام الذات طوال اليوم", flavor: "انتصار واحد قبل الفطور، تحقّق بالفعل." },
  },
  {
    rarity: "common",
    ru: { item: "Список из трёх дел", buff: "+25 к продуктивности, снят паралич выбора", flavor: "Не десять. Три." },
    en: { item: "A list of three tasks", buff: "+25 Productivity, choice paralysis removed", flavor: "Not ten. Three." },
    es: { item: "Una lista de tres tareas", buff: "+25 de productividad, parálisis por decisión eliminada", flavor: "No diez. Tres." },
    fr: { item: "Une liste de trois tâches", buff: "+25 en productivité, paralysie du choix retirée", flavor: "Pas dix. Trois." },
    zh: { item: "三件事的清单", buff: "+25 生产力，消除选择困难", flavor: "不是十件。三件。" },
    hi: { item: "तीन कामों की सूची", buff: "+25 उत्पादकता, चुनाव-लकवा हटा", flavor: "दस नहीं। तीन।" },
    ar: { item: "قائمة من ثلاث مهام", buff: "+25 للإنتاجية، إزالة شلل الاختيار", flavor: "ليست عشرًا. ثلاثًا." },
  },
  {
    rarity: "common",
    ru: { item: "Телефон в другой комнате", buff: "+40 к вниманию на один час", flavor: "Он тебя подождёт. Честно." },
    en: { item: "Phone in another room", buff: "+40 Attention for one hour", flavor: "It will wait for you. Honest." },
    es: { item: "El móvil en otra habitación", buff: "+40 de atención durante una hora", flavor: "Te esperará. De verdad." },
    fr: { item: "Le téléphone dans une autre pièce", buff: "+40 en attention pendant une heure", flavor: "Il t’attendra. Promis." },
    zh: { item: "把手机放到另一个房间", buff: "+40 专注力，持续一小时", flavor: "它会等你的。真的。" },
    hi: { item: "फ़ोन दूसरे कमरे में", buff: "+40 ध्यान, एक घंटे के लिए", flavor: "वह आपका इंतज़ार करेगा। सच में।" },
    ar: { item: "الهاتف في غرفة أخرى", buff: "+40 للانتباه لمدة ساعة", flavor: "سينتظرك. حقًّا." },
  },
  {
    rarity: "common",
    ru: { item: "Пять глубоких вдохов", buff: "−35 к тревоге, +10 к голосу разума", flavor: "Вдох на 4, выдох на 6. Повтори." },
    en: { item: "Five deep breaths", buff: "−35 Anxiety, +10 Voice of Reason", flavor: "In for 4, out for 6. Repeat." },
    es: { item: "Cinco respiraciones profundas", buff: "−35 de ansiedad, +10 de sensatez", flavor: "Inhala en 4, exhala en 6. Repite." },
    fr: { item: "Cinq respirations profondes", buff: "−35 en anxiété, +10 en voix de la raison", flavor: "Inspire sur 4, expire sur 6. Recommence." },
    zh: { item: "五次深呼吸", buff: "−35 焦虑，+10 理智之声", flavor: "吸气 4 秒，呼气 6 秒。重复。" },
    hi: { item: "पाँच गहरी साँसें", buff: "−35 चिंता, +10 विवेक की आवाज़", flavor: "4 तक साँस लें, 6 तक छोड़ें। दोहराएँ।" },
    ar: { item: "خمسة أنفاس عميقة", buff: "−35 للقلق، +10 لصوت العقل", flavor: "شهيق على 4، زفير على 6. كرّر." },
  },
  {
    rarity: "common",
    ru: { item: "Свежие носки", buff: "+8 к настроению, +5 к ощущению, что жизнь налаживается", flavor: "Мелочь, а работает." },
    en: { item: "Fresh socks", buff: "+8 Mood, +5 sense that life is coming together", flavor: "Small thing, works anyway." },
    es: { item: "Calcetines limpios", buff: "+8 de ánimo, +5 de sensación de que la vida se ordena", flavor: "Una tontería, pero funciona." },
    fr: { item: "Des chaussettes propres", buff: "+8 en humeur, +5 au sentiment que la vie s’arrange", flavor: "Un détail, mais ça marche." },
    zh: { item: "干净的袜子", buff: "+8 心情，+5「生活在好转」的感觉", flavor: "小事，但真的有用。" },
    hi: { item: "ताज़े मोज़े", buff: "+8 मूड, +5 «ज़िंदगी पटरी पर आ रही है» का एहसास", flavor: "छोटी बात, फिर भी काम करती है।" },
    ar: { item: "جوارب نظيفة", buff: "+8 للمزاج، +5 لإحساس أن الحياة تنتظم", flavor: "شيء بسيط، لكنه ينفع." },
  },
  {
    rarity: "common",
    ru: { item: "Помытая посуда", buff: "+18 к спокойствию, раковина больше не смотрит с укором", flavor: "Будущий ты скажет спасибо." },
    en: { item: "Washed dishes", buff: "+18 Calm, the sink stops glaring at you", flavor: "Future you says thanks." },
    es: { item: "Los platos fregados", buff: "+18 de calma, el fregadero deja de mirarte mal", flavor: "Tu yo del futuro te lo agradece." },
    fr: { item: "La vaisselle faite", buff: "+18 en sérénité, l’évier arrête de te fixer", flavor: "Ton toi du futur te remercie." },
    zh: { item: "洗好的碗", buff: "+18 平静，水槽不再瞪你", flavor: "未来的你会感谢你。" },
    hi: { item: "धुले हुए बर्तन", buff: "+18 शांति, सिंक अब घूरना बंद करता है", flavor: "भविष्य का आप शुक्रिया कहता है।" },
    ar: { item: "أطباق مغسولة", buff: "+18 للهدوء، حوض المطبخ يكفّ عن توبيخك", flavor: "أنت في المستقبل تشكرك." },
  },
  {
    rarity: "common",
    ru: { item: "Приём пищи без экрана", buff: "+15 к насыщению, +10 к вкусу еды", flavor: "Ты помнишь, что ел вчера на обед?" },
    en: { item: "A meal with no screen", buff: "+15 Satiety, +10 Flavor", flavor: "Do you remember yesterday’s lunch?" },
    es: { item: "Una comida sin pantalla", buff: "+15 de saciedad, +10 de sabor", flavor: "¿Te acuerdas de qué almorzaste ayer?" },
    fr: { item: "Un repas sans écran", buff: "+15 en satiété, +10 en goût", flavor: "Tu te souviens de ton déjeuner d’hier ?" },
    zh: { item: "一顿不看屏幕的饭", buff: "+15 饱腹感，+10 味觉", flavor: "你还记得昨天午饭吃了什么吗？" },
    hi: { item: "बिना स्क्रीन के भोजन", buff: "+15 तृप्ति, +10 स्वाद", flavor: "कल का दोपहर का खाना याद है?" },
    ar: { item: "وجبة بلا شاشة", buff: "+15 للشبع، +10 للنكهة", flavor: "هل تتذكّر غداء الأمس؟" },
  },
  {
    rarity: "common",
    ru: { item: "Будильник на 15 минут раньше", buff: "+20 к утреннему спокойствию, снят режим «опаздываю»", flavor: "Утро без спешки — забытая роскошь." },
    en: { item: "Alarm 15 minutes earlier", buff: "+20 Morning Calm, «running late» mode removed", flavor: "An unhurried morning is a forgotten luxury." },
    es: { item: "La alarma 15 minutos antes", buff: "+20 de calma matinal, modo «voy tarde» eliminado", flavor: "Una mañana sin prisas es un lujo olvidado." },
    fr: { item: "Le réveil 15 minutes plus tôt", buff: "+20 en calme matinal, mode «en retard» retiré", flavor: "Un matin sans hâte est un luxe oublié." },
    zh: { item: "闹钟提前 15 分钟", buff: "+20 清晨平静，移除「要迟到了」模式", flavor: "不慌不忙的早晨是被遗忘的奢侈。" },
    hi: { item: "अलार्म 15 मिनट पहले", buff: "+20 सुबह की शांति, «देर हो रही है» मोड हटा", flavor: "बिना जल्दबाज़ी वाली सुबह एक भूली हुई ऐश है।" },
    ar: { item: "المنبّه أبكر بـ15 دقيقة", buff: "+20 لهدوء الصباح، إزالة وضع «تأخّرت»", flavor: "صباح بلا عجلة رفاهية منسيّة." },
  },
  {
    rarity: "common",
    ru: { item: "Разобранный рабочий стол", buff: "+22 к фокусу, −50% к фразе «где эта бумажка»", flavor: "Внешний порядок ведёт к внутреннему." },
    en: { item: "A cleared desk", buff: "+22 Focus, −50% «where is that paper»", flavor: "Outer order leads to inner order." },
    es: { item: "El escritorio despejado", buff: "+22 de concentración, −50% de «¿dónde está ese papel?»", flavor: "El orden de fuera trae el de dentro." },
    fr: { item: "Un bureau dégagé", buff: "+22 en concentration, −50 % de «où est ce papier»", flavor: "L’ordre extérieur mène à l’ordre intérieur." },
    zh: { item: "收拾干净的桌面", buff: "+22 专注，−50%「那张纸哪去了」", flavor: "外在的秩序带来内在的秩序。" },
    hi: { item: "साफ़ किया हुआ डेस्क", buff: "+22 फ़ोकस, −50% «वो काग़ज़ कहाँ है»", flavor: "बाहरी व्यवस्था भीतरी व्यवस्था लाती है।" },
    ar: { item: "مكتب مرتّب", buff: "+22 للتركيز، −50% لـ«أين تلك الورقة»", flavor: "النظام في الخارج يقود إلى النظام في الداخل." },
  },
  {
    rarity: "common",
    ru: { item: "Один разговор вслух", buff: "+15 к социальной энергии", flavor: "Позвони тому, о ком подумал." },
    en: { item: "One conversation out loud", buff: "+15 Social Energy", flavor: "Call the person you just thought of." },
    es: { item: "Una conversación en voz alta", buff: "+15 de energía social", flavor: "Llama a la persona en la que acabas de pensar." },
    fr: { item: "Une conversation à voix haute", buff: "+15 en énergie sociale", flavor: "Appelle la personne à qui tu viens de penser." },
    zh: { item: "一次开口的交谈", buff: "+15 社交能量", flavor: "给你刚想到的那个人打电话。" },
    hi: { item: "ज़ोर से एक बातचीत", buff: "+15 सामाजिक ऊर्जा", flavor: "जिसके बारे में अभी सोचा, उसे कॉल करें।" },
    ar: { item: "محادثة واحدة بصوت عالٍ", buff: "+15 للطاقة الاجتماعية", flavor: "اتّصل بالشخص الذي خطر ببالك للتو." },
  },
  {
    rarity: "common",
    ru: { item: "Пятиминутная растяжка", buff: "+14 к подвижности, −20 к «тело как деревяшка»", flavor: "Спина у тебя одна." },
    en: { item: "A five-minute stretch", buff: "+14 Mobility, −20 «body like a plank»", flavor: "You only get one spine." },
    es: { item: "Cinco minutos de estiramientos", buff: "+14 de movilidad, −20 de «cuerpo de madera»", flavor: "Solo tienes una columna." },
    fr: { item: "Cinq minutes d’étirements", buff: "+14 en mobilité, −20 de «corps en planche»", flavor: "Tu n’as qu’une seule colonne." },
    zh: { item: "五分钟拉伸", buff: "+14 灵活度，−20「身体像木板」", flavor: "脊椎只有一根。" },
    hi: { item: "पाँच मिनट की स्ट्रेचिंग", buff: "+14 लचीलापन, −20 «शरीर तख़्ते जैसा»", flavor: "रीढ़ एक ही है।" },
    ar: { item: "تمدّد لخمس دقائق", buff: "+14 للمرونة، −20 لـ«جسد كاللوح»", flavor: "لديك عمود فقري واحد فقط." },
  },

  // ── rare ────────────────────────────────────────────────────
  {
    rarity: "rare",
    ru: { item: "Камень социализации", buff: "+10 к социальным навыкам, первый разговор без дебаффа «неловкость»", flavor: "Держи в кармане. Просто знай, что он там." },
    en: { item: "Stone of Socializing", buff: "+10 Social Skills, first conversation with no «awkwardness» debuff", flavor: "Keep it in your pocket. Just know it is there." },
    es: { item: "Piedra de la Sociabilidad", buff: "+10 de habilidades sociales; la primera charla sin la penalización «incomodidad»", flavor: "Llévala en el bolsillo. Basta con saber que está ahí." },
    fr: { item: "Pierre de Sociabilité", buff: "+10 en aptitudes sociales ; première conversation sans le malus «gêne»", flavor: "Garde-la dans ta poche. Sache juste qu’elle est là." },
    zh: { item: "社交之石", buff: "+10 社交技能，第一次交谈免除「尴尬」减益", flavor: "放在口袋里。知道它在就够了。" },
    hi: { item: "सामाजिकता का पत्थर", buff: "+10 सामाजिक कौशल; पहली बातचीत «असहजता» डीबफ़ के बिना", flavor: "जेब में रखें। बस पता हो कि वह वहाँ है।" },
    ar: { item: "حجر التواصل الاجتماعي", buff: "+10 لمهارات التواصل، وأول محادثة بلا تأثير «الإحراج»", flavor: "احتفظ به في جيبك. يكفي أن تعرف أنه هناك." },
  },
  {
    rarity: "rare",
    ru: { item: "Амулет отказа", buff: "+30 к личным границам, −100% к обязательствам, которые тебе не нужны", flavor: "«Нет» — это законченное предложение." },
    en: { item: "Amulet of Refusal", buff: "+30 Boundaries, −100% obligations you do not want", flavor: "«No» is a complete sentence." },
    es: { item: "Amuleto del Rechazo", buff: "+30 de límites personales, −100% de compromisos que no quieres", flavor: "«No» es una frase completa." },
    fr: { item: "Amulette du Refus", buff: "+30 en limites personnelles, −100 % d’obligations non voulues", flavor: "«Non» est une phrase complète." },
    zh: { item: "拒绝护符", buff: "+30 个人边界，−100% 你不想要的义务", flavor: "「不」本身就是一句完整的话。" },
    hi: { item: "इनकार का ताबीज़", buff: "+30 सीमाएँ, −100% वे ज़िम्मेदारियाँ जो आप नहीं चाहते", flavor: "«नहीं» अपने आप में पूरा वाक्य है।" },
    ar: { item: "تعويذة الرفض", buff: "+30 للحدود الشخصية، −100% للالتزامات التي لا تريدها", flavor: "«لا» جملة كاملة بذاتها." },
  },
  {
    rarity: "rare",
    ru: { item: "Восьмичасовой сон", buff: "+50 ко всем характеристикам до вечера", flavor: "Самый душный бафф в игре. И самый сильный." },
    en: { item: "Eight hours of sleep", buff: "+50 to every stat until evening", flavor: "The most boring buff in the game. And the strongest." },
    es: { item: "Ocho horas de sueño", buff: "+50 a todas las estadísticas hasta la noche", flavor: "El buff más aburrido del juego. Y el más fuerte." },
    fr: { item: "Huit heures de sommeil", buff: "+50 à toutes les stats jusqu’au soir", flavor: "Le buff le plus ennuyeux du jeu. Et le plus puissant." },
    zh: { item: "八小时睡眠", buff: "+50 到所有属性，持续到晚上", flavor: "游戏里最无聊的增益。也是最强的。" },
    hi: { item: "आठ घंटे की नींद", buff: "+50 हर स्टैट में, शाम तक", flavor: "खेल का सबसे उबाऊ बफ़। और सबसे ताक़तवर भी।" },
    ar: { item: "ثماني ساعات نوم", buff: "+50 لكل الإحصاءات حتى المساء", flavor: "أكثر تعزيز مملّ في اللعبة. وأقواها." },
  },
  {
    rarity: "rare",
    ru: { item: "Тренировка на 20 минут", buff: "+35 к энергии, +20 к настроению, +5 к осанке", flavor: "Начни. Разомнёшься по ходу." },
    en: { item: "A 20-minute workout", buff: "+35 Energy, +20 Mood, +5 Posture", flavor: "Just start. You will warm up on the way." },
    es: { item: "Un entrenamiento de 20 minutos", buff: "+35 de energía, +20 de ánimo, +5 de postura", flavor: "Solo empieza. Ya entrarás en calor." },
    fr: { item: "Un entraînement de 20 minutes", buff: "+35 en énergie, +20 en humeur, +5 en posture", flavor: "Commence, c’est tout. L’échauffement viendra en route." },
    zh: { item: "二十分钟锻炼", buff: "+35 精力，+20 心情，+5 体态", flavor: "先动起来。热身会自己跟上。" },
    hi: { item: "20 मिनट की कसरत", buff: "+35 ऊर्जा, +20 मूड, +5 मुद्रा", flavor: "बस शुरू करें। वॉर्म-अप रास्ते में हो जाएगा।" },
    ar: { item: "تمرين عشرين دقيقة", buff: "+35 للطاقة، +20 للمزاج، +5 لاستقامة الجسم", flavor: "ابدأ فقط. سيأتيك الإحماء في الطريق." },
  },
  {
    rarity: "rare",
    ru: { item: "Свиток завершения", buff: "+40 к удовлетворению, снят дебафф «десять вкладок в голове»", flavor: "Доведи хоть что-то до финала сегодня." },
    en: { item: "Scroll of Completion", buff: "+40 Satisfaction, «ten tabs open in your head» debuff removed", flavor: "Finish just one thing today." },
    es: { item: "Pergamino de la Conclusión", buff: "+40 de satisfacción, penalización «diez pestañas abiertas en la cabeza» eliminada", flavor: "Termina solo una cosa hoy." },
    fr: { item: "Parchemin de l’Achèvement", buff: "+40 en satisfaction, malus «dix onglets ouverts dans la tête» retiré", flavor: "Termine une seule chose aujourd’hui." },
    zh: { item: "完成之卷", buff: "+40 满足感，移除「脑子里开着十个标签页」减益", flavor: "今天至少做完一件事。" },
    hi: { item: "पूर्णता का स्क्रॉल", buff: "+40 संतोष, «दिमाग़ में दस टैब खुले» डीबफ़ हटा", flavor: "आज बस एक काम पूरा करें।" },
    ar: { item: "لفيفة الإنجاز", buff: "+40 للرضا، إزالة تأثير «عشرة تبويبات مفتوحة في رأسك»", flavor: "أنجز شيئًا واحدًا فقط اليوم." },
  },
  {
    rarity: "rare",
    ru: { item: "Эликсир раннего часа", buff: "+30 к завтрашнему тебе", flavor: "Ложись до полуночи. Завтрашний ты — тоже ты." },
    en: { item: "Elixir of the Early Hour", buff: "+30 to tomorrow’s you", flavor: "Be in bed before midnight. Tomorrow’s you is still you." },
    es: { item: "Elixir de la Hora Temprana", buff: "+30 a tu yo de mañana", flavor: "A la cama antes de medianoche. Tu yo de mañana también eres tú." },
    fr: { item: "Élixir de l’Heure Matinale", buff: "+30 à ton toi de demain", flavor: "Au lit avant minuit. Ton toi de demain, c’est encore toi." },
    zh: { item: "早时辰药剂", buff: "+30 给明天的你", flavor: "午夜前上床。明天的你也是你。" },
    hi: { item: "सवेरे की घड़ी का अमृत", buff: "+30 कल के आपको", flavor: "आधी रात से पहले बिस्तर में। कल का आप भी आप ही है।" },
    ar: { item: "إكسير الساعة الباكرة", buff: "+30 لنسختك في الغد", flavor: "إلى السرير قبل منتصف الليل. أنت في الغد ما زلت أنت." },
  },
  {
    rarity: "rare",
    ru: { item: "Перчатки честного разговора", buff: "+25 к отношениям, снята накопленная обида уровня 3", flavor: "Скажи то, что откладывал две недели." },
    en: { item: "Gloves of the Honest Talk", buff: "+25 Relationship, level-3 stored resentment cleared", flavor: "Say the thing you have put off for two weeks." },
    es: { item: "Guantes de la Conversación Sincera", buff: "+25 de relación, resentimiento acumulado de nivel 3 eliminado", flavor: "Di eso que llevas dos semanas posponiendo." },
    fr: { item: "Gants de la Discussion Franche", buff: "+25 en relation, rancœur accumulée de niveau 3 dissipée", flavor: "Dis la chose que tu repousses depuis deux semaines." },
    zh: { item: "坦诚对话手套", buff: "+25 关系，清除 3 级积压的怨气", flavor: "说出那件你拖了两周的事。" },
    hi: { item: "ईमानदार बातचीत के दस्ताने", buff: "+25 रिश्ता, स्तर-3 का जमा हुआ गिला साफ़", flavor: "वो बात कह दें जो दो हफ़्ते से टाल रहे हैं।" },
    ar: { item: "قفازات الحديث الصريح", buff: "+25 للعلاقة، وإزالة استياء متراكم من المستوى 3", flavor: "قل الشيء الذي أجّلته منذ أسبوعين." },
  },
  {
    rarity: "rare",
    ru: { item: "Плащ тишины", buff: "+20 к присутствию в моменте, +15 к случайным хорошим мыслям", flavor: "Погуляй без наушников. Тишина тоже что-то говорит." },
    en: { item: "Cloak of Silence", buff: "+20 Presence, +15 random good ideas", flavor: "Take a walk with no headphones. Silence says things too." },
    es: { item: "Capa del Silencio", buff: "+20 de presencia, +15 de buenas ideas al azar", flavor: "Sal a caminar sin auriculares. El silencio también dice cosas." },
    fr: { item: "Cape du Silence", buff: "+20 en présence, +15 en bonnes idées aléatoires", flavor: "Marche sans écouteurs. Le silence aussi a des choses à dire." },
    zh: { item: "静默之披风", buff: "+20 临在感，+15 随机好点子", flavor: "不戴耳机去散个步。沉默也会说话。" },
    hi: { item: "मौन का लबादा", buff: "+20 उपस्थिति, +15 अचानक आने वाले अच्छे विचार", flavor: "बिना हेडफ़ोन टहलें। ख़ामोशी भी कुछ कहती है।" },
    ar: { item: "عباءة الصمت", buff: "+20 للحضور، +15 لأفكار جيدة عشوائية", flavor: "تمشَّ بلا سمّاعات. الصمت يقول أشياء أيضًا." },
  },
  {
    rarity: "rare",
    ru: { item: "Кольцо уединения", buff: "+45 к глубокой работе на 90 минут", flavor: "Режим «в самолёте» на полтора часа. Мир не рухнет." },
    en: { item: "Ring of Seclusion", buff: "+45 Deep Work for 90 minutes", flavor: "Airplane mode for an hour and a half. The world holds." },
    es: { item: "Anillo del Aislamiento", buff: "+45 de trabajo profundo durante 90 minutos", flavor: "Modo avión hora y media. El mundo aguanta." },
    fr: { item: "Anneau de la Retraite", buff: "+45 en travail profond pendant 90 minutes", flavor: "Mode avion pendant une heure et demie. Le monde tient." },
    zh: { item: "独处之戒", buff: "+45 深度工作，持续 90 分钟", flavor: "开飞行模式一个半小时。世界不会塌。" },
    hi: { item: "एकांत की अंगूठी", buff: "+45 गहरा काम, 90 मिनट के लिए", flavor: "डेढ़ घंटा एयरप्लेन मोड। दुनिया टिकी रहेगी।" },
    ar: { item: "خاتم العزلة", buff: "+45 للعمل العميق لمدة 90 دقيقة", flavor: "وضع الطيران لساعة ونصف. العالم سيصمد." },
  },
  {
    rarity: "rare",
    ru: { item: "Записная книжка благодарности", buff: "+20 к базовому уровню счастья", flavor: "Три вещи за сегодня. Даже маленькие." },
    en: { item: "Gratitude Notebook", buff: "+20 baseline Happiness", flavor: "Three things from today. Small ones count." },
    es: { item: "Cuaderno de Gratitud", buff: "+20 de felicidad base", flavor: "Tres cosas de hoy. Las pequeñas cuentan." },
    fr: { item: "Carnet de Gratitude", buff: "+20 de bonheur de base", flavor: "Trois choses d’aujourd’hui. Les petites comptent." },
    zh: { item: "感恩笔记本", buff: "+20 幸福感基线", flavor: "今天的三件事。小事也算。" },
    hi: { item: "कृतज्ञता की डायरी", buff: "+20 बुनियादी ख़ुशी", flavor: "आज की तीन बातें। छोटी भी गिनती में हैं।" },
    ar: { item: "دفتر الامتنان", buff: "+20 لمستوى السعادة الأساسي", flavor: "ثلاثة أشياء من اليوم. الصغيرة تُحتسب أيضًا." },
  },
  {
    rarity: "rare",
    ru: { item: "Оберег покоя", buff: "−60% к фантомной тревоге, +30 к вниманию", flavor: "Выключи уведомления. Красные кружочки тебе не начальники." },
    en: { item: "Charm of Quiet", buff: "−60% phantom anxiety, +30 Attention", flavor: "Turn off notifications. Red badges are not your boss." },
    es: { item: "Amuleto de la Calma", buff: "−60% de ansiedad fantasma, +30 de atención", flavor: "Apaga las notificaciones. Los globitos rojos no son tu jefe." },
    fr: { item: "Talisman du Calme", buff: "−60 % d’anxiété fantôme, +30 en attention", flavor: "Coupe les notifications. Les pastilles rouges ne sont pas ton patron." },
    zh: { item: "安宁护符", buff: "−60% 幻觉焦虑，+30 专注力", flavor: "关掉通知。红点不是你老板。" },
    hi: { item: "शांति का तावीज़", buff: "−60% काल्पनिक चिंता, +30 ध्यान", flavor: "नोटिफ़िकेशन बंद करें। लाल घेरे आपके बॉस नहीं हैं।" },
    ar: { item: "تميمة السكينة", buff: "−60% للقلق الوهمي، +30 للانتباه", flavor: "أطفئ الإشعارات. الدوائر الحمراء ليست مديرك." },
  },
  {
    rarity: "rare",
    ru: { item: "Фляга полуденного привала", buff: "+25 к выносливости во второй половине дня", flavor: "Сделай перерыв на обед. Работать сквозь него — не флекс." },
    en: { item: "Flask of the Midday Rest", buff: "+25 Stamina for the afternoon", flavor: "Take a real lunch break. Working through it is not a flex." },
    es: { item: "Cantimplora del Descanso del Mediodía", buff: "+25 de aguante para la tarde", flavor: "Haz una pausa de verdad para comer. Saltártela no es de valientes." },
    fr: { item: "Gourde de la Pause de Midi", buff: "+25 en endurance pour l’après-midi", flavor: "Fais une vraie pause déjeuner. Sauter le repas n’a rien d’héroïque." },
    zh: { item: "午间小憩之壶", buff: "+25 下午的耐力", flavor: "好好吃个午饭。硬扛过去不值得炫耀。" },
    hi: { item: "दोपहर के विश्राम की बोतल", buff: "+25 दोपहर के लिए सहनशक्ति", flavor: "खाने का असली ब्रेक लें। उसे छोड़ना कोई कमाल नहीं।" },
    ar: { item: "قارورة استراحة الظهيرة", buff: "+25 للقدرة على التحمّل بعد الظهر", flavor: "خذ استراحة غداء حقيقية. العمل من دونها ليس إنجازًا." },
  },

  // ── epic ────────────────────────────────────────────────────
  {
    rarity: "epic",
    ru: { item: "Печать финансовой ясности", buff: "+40 к спокойствию: ты наконец знаешь, сколько тратишь", flavor: "Открой банковское приложение. Посмотри честно." },
    en: { item: "Seal of Financial Clarity", buff: "+40 Calm: you finally know what you spend", flavor: "Open your banking app. Look honestly." },
    es: { item: "Sello de la Claridad Financiera", buff: "+40 de calma: por fin sabes cuánto gastas", flavor: "Abre la app del banco. Míralo con honestidad." },
    fr: { item: "Sceau de la Clarté Financière", buff: "+40 en sérénité : tu sais enfin ce que tu dépenses", flavor: "Ouvre ton appli bancaire. Regarde honnêtement." },
    zh: { item: "财务清明之印", buff: "+40 平静：你终于知道自己花了多少", flavor: "打开银行 App。诚实地看一眼。" },
    hi: { item: "वित्तीय स्पष्टता की मुहर", buff: "+40 शांति: आख़िरकार पता है कि कितना ख़र्च होता है", flavor: "बैंक ऐप खोलें। ईमानदारी से देखें।" },
    ar: { item: "ختم الوضوح المالي", buff: "+40 للهدوء: أخيرًا تعرف كم تُنفق", flavor: "افتح تطبيق البنك. انظر بصدق." },
  },
  {
    rarity: "epic",
    ru: { item: "Меч возвращённых часов", buff: "+2 часа к жизни ежедневно, снят дебафф «бесконечная лента»", flavor: "Удали одно приложение. Ты знаешь, какое именно." },
    en: { item: "Sword of Reclaimed Hours", buff: "+2 hours of life per day, «infinite feed» debuff removed", flavor: "Delete one app. You know exactly which one." },
    es: { item: "Espada de las Horas Recuperadas", buff: "+2 horas de vida al día, penalización «feed infinito» eliminada", flavor: "Borra una app. Sabes cuál exactamente." },
    fr: { item: "Épée des Heures Reconquises", buff: "+2 heures de vie par jour, malus «fil infini» retiré", flavor: "Supprime une appli. Tu sais très bien laquelle." },
    zh: { item: "夺回时光之剑", buff: "每天 +2 小时人生，移除「无限信息流」减益", flavor: "删掉一个 App。你很清楚是哪个。" },
    hi: { item: "वापस पाए घंटों की तलवार", buff: "रोज़ +2 घंटे ज़िंदगी, «अंतहीन फ़ीड» डीबफ़ हटा", flavor: "एक ऐप हटाएँ। आप जानते हैं कौन-सा।" },
    ar: { item: "سيف الساعات المستردّة", buff: "+ساعتان من العمر يوميًا، إزالة تأثير «الخلاصة اللانهائية»", flavor: "احذف تطبيقًا واحدًا. تعرف أيّها بالضبط." },
  },
  {
    rarity: "epic",
    ru: { item: "Мантия ранних планов на выходные", buff: "+50 к предвкушению, суббота больше не растворяется в никуда", flavor: "Запланируй одно хорошее дело заранее." },
    en: { item: "Mantle of Early Weekend Plans", buff: "+50 Anticipation, Saturday stops dissolving into nothing", flavor: "Plan one good thing in advance." },
    es: { item: "Manto de los Planes de Finde por Adelantado", buff: "+50 de ilusión, el sábado deja de disolverse en la nada", flavor: "Planea una cosa buena con antelación." },
    fr: { item: "Manteau des Projets de Week-end Anticipés", buff: "+50 en impatience, le samedi cesse de se dissoudre dans le vide", flavor: "Prévois une bonne chose à l’avance." },
    zh: { item: "周末早计划之披风", buff: "+50 期待感，周六不再化为乌有", flavor: "提前安排一件好事。" },
    hi: { item: "वीकेंड की पहले से योजना का चोगा", buff: "+50 प्रत्याशा, शनिवार यूँ ही ग़ायब होना बंद", flavor: "एक अच्छी चीज़ पहले से तय कर लें।" },
    ar: { item: "رداء خطط نهاية الأسبوع المبكرة", buff: "+50 للترقّب، السبت يتوقّف عن التبخّر إلى لا شيء", flavor: "خطّط لشيء جميل مسبقًا." },
  },
  {
    rarity: "epic",
    ru: { item: "Талисман здравия", buff: "−80% к фоновому «надо бы провериться»", flavor: "Запишись на тот приём, что тянешь с весны." },
    en: { item: "Talisman of Wellbeing", buff: "−80% background «I should get that checked»", flavor: "Book the appointment you have dodged since spring." },
    es: { item: "Talismán del Bienestar", buff: "−80% del «debería hacerme mirar eso» de fondo", flavor: "Pide la cita que llevas esquivando desde primavera." },
    fr: { item: "Talisman du Bien-être", buff: "−80 % du «je devrais faire vérifier ça» en fond", flavor: "Prends le rendez-vous que tu évites depuis le printemps." },
    zh: { item: "康健护身符", buff: "−80% 后台运行的「该去查查了」", flavor: "把你从春天拖到现在的那个预约挂了。" },
    hi: { item: "स्वास्थ्य का तावीज़", buff: "−80% पृष्ठभूमि में चल रहा «यह जँचवा लेना चाहिए»", flavor: "वो अपॉइंटमेंट बुक करें जिसे वसंत से टाल रहे हैं।" },
    ar: { item: "تعويذة العافية", buff: "−80% من هاجس «يجب أن أفحص هذا»", flavor: "احجز الموعد الذي تتهرّب منه منذ الربيع." },
  },
  {
    rarity: "epic",
    ru: { item: "Гримуар одной книги", buff: "+30 к вниманию, +25 к разговорам за ужином", flavor: "20 страниц в день — это книга в неделю." },
    en: { item: "Grimoire of One Book", buff: "+30 Attention, +25 dinner conversation", flavor: "20 pages a day is a book a week." },
    es: { item: "Grimorio de Un Solo Libro", buff: "+30 de atención, +25 de conversación en la cena", flavor: "20 páginas al día son un libro a la semana." },
    fr: { item: "Grimoire d’un Seul Livre", buff: "+30 en attention, +25 en conversation à table", flavor: "20 pages par jour, c’est un livre par semaine." },
    zh: { item: "一本书的魔典", buff: "+30 专注力，+25 餐桌谈资", flavor: "每天 20 页，一周一本书。" },
    hi: { item: "एक किताब की ग्रिमोआ", buff: "+30 ध्यान, +25 डिनर की बातचीत", flavor: "रोज़ 20 पन्ने यानी हफ़्ते में एक किताब।" },
    ar: { item: "كتاب السحر ذو المجلّد الواحد", buff: "+30 للانتباه، +25 لحديث العشاء", flavor: "20 صفحة يوميًا تعني كتابًا كل أسبوع." },
  },
  {
    rarity: "epic",
    ru: { item: "Ключ от пустых полок", buff: "+35 к лёгкости, −1 мешок вещей, которые тянули вниз", flavor: "Разбери шкаф. Не носил год — не наденешь." },
    en: { item: "Key to Empty Shelves", buff: "+35 Lightness, −1 bag of stuff that weighed you down", flavor: "Clear out the closet. Not worn in a year, never will be." },
    es: { item: "Llave de los Estantes Vacíos", buff: "+35 de ligereza, −1 bolsa de cosas que te pesaban", flavor: "Vacía el armario. Si no lo usaste en un año, no lo harás." },
    fr: { item: "Clé des Étagères Vides", buff: "+35 en légèreté, −1 sac d’affaires qui te plombaient", flavor: "Vide le placard. Pas porté depuis un an, ça ne changera pas." },
    zh: { item: "空架之钥", buff: "+35 轻盈感，−1 袋拖累你的杂物", flavor: "清一清衣柜。一年没穿的，以后也不会穿。" },
    hi: { item: "ख़ाली अलमारियों की चाबी", buff: "+35 हल्कापन, −1 बोरा उस सामान का जो नीचे खींच रहा था", flavor: "अलमारी ख़ाली करें। साल भर नहीं पहना, तो आगे भी नहीं।" },
    ar: { item: "مفتاح الرفوف الفارغة", buff: "+35 للخفّة، −1 كيس من الأشياء التي تثقلك", flavor: "أفرغ الخزانة. ما لم تلبسه منذ عام لن تلبسه." },
  },
  {
    rarity: "epic",
    ru: { item: "Компас нового маршрута", buff: "+40 к любопытству, мозг строит свежие тропы", flavor: "Пройди домой другой дорогой." },
    en: { item: "Compass of the New Route", buff: "+40 Curiosity, your brain lays fresh paths", flavor: "Walk home a different way." },
    es: { item: "Brújula de la Ruta Nueva", buff: "+40 de curiosidad, tu cerebro traza caminos nuevos", flavor: "Vuelve a casa por otro camino." },
    fr: { item: "Boussole de l’Itinéraire Nouveau", buff: "+40 en curiosité, ton cerveau trace de nouveaux chemins", flavor: "Rentre par un autre chemin." },
    zh: { item: "新路径罗盘", buff: "+40 好奇心，大脑铺出新的通路", flavor: "换一条路回家。" },
    hi: { item: "नए रास्ते का कम्पास", buff: "+40 जिज्ञासा, दिमाग़ नई राहें बनाता है", flavor: "घर किसी और रास्ते से जाएँ।" },
    ar: { item: "بوصلة الطريق الجديد", buff: "+40 للفضول، دماغك يشقّ مسارات جديدة", flavor: "عُد إلى البيت من طريق مختلف." },
  },
  {
    rarity: "epic",
    ru: { item: "Свиток примирения", buff: "+60 к отношениям, снят дебафф «холодная война» с близким", flavor: "Извинись первым. Гордость — плохая валюта." },
    en: { item: "Scroll of Reconciliation", buff: "+60 Relationship, «cold war» debuff with someone close removed", flavor: "Apologize first. Pride is a poor currency." },
    es: { item: "Pergamino de la Reconciliación", buff: "+60 de relación, penalización «guerra fría» con alguien cercano eliminada", flavor: "Discúlpate primero. El orgullo es mala moneda." },
    fr: { item: "Parchemin de la Réconciliation", buff: "+60 en relation, malus «guerre froide» avec un proche retiré", flavor: "Excuse-toi le premier. L’orgueil est une piètre monnaie." },
    zh: { item: "和解之卷", buff: "+60 关系，移除与亲近之人的「冷战」减益", flavor: "先道歉。骄傲是很差的货币。" },
    hi: { item: "मेल-मिलाप का स्क्रॉल", buff: "+60 रिश्ता, किसी क़रीबी से «शीत युद्ध» डीबफ़ हटा", flavor: "पहले माफ़ी माँग लें। घमंड घटिया मुद्रा है।" },
    ar: { item: "لفيفة المصالحة", buff: "+60 للعلاقة، إزالة تأثير «الحرب الباردة» مع شخص قريب", flavor: "اعتذر أولًا. الكبرياء عملة رديئة." },
  },

  // ── legendary ───────────────────────────────────────────────
  {
    rarity: "legendary",
    ru: { item: "Венец семи рассветов", buff: "+100 к энергии, циркадный ритм перекалиброван", flavor: "Ложись и вставай в один час семь дней подряд. Почти никто не доносит." },
    en: { item: "Crown of Seven Dawns", buff: "+100 Energy, circadian rhythm recalibrated", flavor: "Same sleep and wake time, seven days straight. Almost nobody makes it." },
    es: { item: "Corona de los Siete Amaneceres", buff: "+100 de energía, ritmo circadiano recalibrado", flavor: "Misma hora de dormir y despertar, siete días seguidos. Casi nadie lo logra." },
    fr: { item: "Couronne des Sept Aurores", buff: "+100 en énergie, rythme circadien recalibré", flavor: "Même heure de coucher et de lever, sept jours d’affilée. Presque personne n’y arrive." },
    zh: { item: "七度黎明之冠", buff: "+100 精力，昼夜节律重新校准", flavor: "连续七天同一时间睡、同一时间起。几乎没人做到。" },
    hi: { item: "सात भोरों का मुकुट", buff: "+100 ऊर्जा, सर्कैडियन लय फिर से सधी", flavor: "सात दिन लगातार एक ही समय सोना-जागना। शायद ही कोई कर पाता है।" },
    ar: { item: "تاج الفجور السبعة", buff: "+100 للطاقة، معايرة الإيقاع اليومي من جديد", flavor: "الوقت نفسه للنوم والاستيقاظ، سبعة أيام متتالية. لا يكاد أحد ينجح." },
  },
  {
    rarity: "legendary",
    ru: { item: "Реликвия ясного пути", buff: "+80 к направлению, туман целей рассеян", flavor: "Скажи вслух, чего хочешь от жизни. Хоть себе." },
    en: { item: "Relic of the Clear Path", buff: "+80 Direction, the goal-fog lifts", flavor: "Say out loud what you want from life. Even just to yourself." },
    es: { item: "Reliquia del Camino Claro", buff: "+80 de rumbo, se disipa la niebla de las metas", flavor: "Di en voz alta qué quieres de la vida. Aunque sea solo para ti." },
    fr: { item: "Relique du Chemin Clair", buff: "+80 en direction, le brouillard des objectifs se lève", flavor: "Dis à voix haute ce que tu veux de la vie. Ne serait-ce qu’à toi-même." },
    zh: { item: "明路圣物", buff: "+80 方向感，目标的迷雾散去", flavor: "大声说出你想从人生里得到什么。哪怕只说给自己听。" },
    hi: { item: "स्पष्ट राह की धरोहर", buff: "+80 दिशा, लक्ष्यों की धुंध छँटती है", flavor: "ज़ोर से कहें कि ज़िंदगी से क्या चाहते हैं। चाहे बस ख़ुद से।" },
    ar: { item: "أثر الطريق الواضح", buff: "+80 للاتجاه، وينقشع ضباب الأهداف", flavor: "قل بصوت مسموع ما تريده من الحياة. ولو لنفسك فقط." },
  },
  {
    rarity: "legendary",
    ru: { item: "Философский камень маленьких шагов", buff: "Превращает «когда-нибудь» в «по чуть-чуть каждый день»", flavor: "5 минут в день бьют 5 часов раз в месяц." },
    en: { item: "Philosopher’s Stone of Small Steps", buff: "Turns «someday» into «a little every day»", flavor: "5 minutes daily beats 5 hours once a month." },
    es: { item: "Piedra Filosofal de los Pequeños Pasos", buff: "Convierte el «algún día» en «un poco cada día»", flavor: "5 minutos al día ganan a 5 horas una vez al mes." },
    fr: { item: "Pierre Philosophale des Petits Pas", buff: "Change le «un jour» en «un peu chaque jour»", flavor: "5 minutes par jour valent mieux que 5 heures une fois par mois." },
    zh: { item: "小步之贤者之石", buff: "把「总有一天」变成「每天一点点」", flavor: "每天 5 分钟，胜过每月一次 5 小时。" },
    hi: { item: "छोटे क़दमों का पारस पत्थर", buff: "«किसी दिन» को «हर दिन थोड़ा-थोड़ा» में बदल देता है", flavor: "रोज़ 5 मिनट, महीने में एक बार के 5 घंटे से बेहतर।" },
    ar: { item: "حجر الفلاسفة للخطوات الصغيرة", buff: "يحوّل «يومًا ما» إلى «قليلًا كل يوم»", flavor: "5 دقائق يوميًا تتفوّق على 5 ساعات مرة في الشهر." },
  },
  {
    rarity: "legendary",
    ru: { item: "Сердце прощения", buff: "−90 к грузу, который таскал годами, +50 ко всему остальному", flavor: "Прости себя за старое. Тот ты делал что мог с тем, что знал тогда." },
    en: { item: "Heart of Forgiveness", buff: "−90 weight you have hauled for years, +50 to everything else", flavor: "Forgive your past self. You did what you could with what you knew then." },
    es: { item: "Corazón del Perdón", buff: "−90 del peso que llevas años cargando, +50 a todo lo demás", flavor: "Perdona a quien fuiste. Hizo lo que pudo con lo que sabía entonces." },
    fr: { item: "Cœur du Pardon", buff: "−90 au poids que tu traînes depuis des années, +50 à tout le reste", flavor: "Pardonne à la personne que tu étais. Elle a fait au mieux avec ce qu’elle savait." },
    zh: { item: "宽恕之心", buff: "−90 你背了多年的重量，+50 其他一切", flavor: "原谅过去的自己。当时的你，用当时所知，已尽了力。" },
    hi: { item: "क्षमा का हृदय", buff: "−90 उस बोझ का जो बरसों से ढो रहे हैं, +50 बाक़ी सब में", flavor: "पुराने ख़ुद को माफ़ कर दें। तब जो पता था, उसी से पूरी कोशिश की थी।" },
    ar: { item: "قلب المغفرة", buff: "−90 من الثقل الذي حملته سنين، +50 لكل ما عداه", flavor: "سامِح نفسك القديمة. فعلت ما استطعت بما كنت تعرفه آنذاك." },
  },
  {
    rarity: "legendary",
    ru: { item: "Печать родного голоса", buff: "+70 к теплу, +∞ к тому, о чём потом не пожалеешь", flavor: "Позвони родителям. Не по поводу — просто узнать, как они." },
    en: { item: "Seal of a Familiar Voice", buff: "+70 Warmth, +∞ to things you will not regret", flavor: "Call your parents. No reason, just to hear how they are." },
    es: { item: "Sello de la Voz Familiar", buff: "+70 de calidez, +∞ a lo que no vas a lamentar", flavor: "Llama a tus padres. Sin motivo, solo para saber cómo están." },
    fr: { item: "Sceau d’une Voix Familière", buff: "+70 en chaleur, +∞ à ce que tu ne regretteras pas", flavor: "Appelle tes parents. Sans raison, juste pour prendre des nouvelles." },
    zh: { item: "熟悉嗓音之印", buff: "+70 温暖，+∞ 你不会后悔的事", flavor: "给父母打个电话。没什么事，就问问他们好不好。" },
    hi: { item: "परिचित आवाज़ की मुहर", buff: "+70 गर्माहट, +∞ उन बातों में जिनका पछतावा नहीं होगा", flavor: "माता-पिता को फ़ोन करें। कोई वजह नहीं, बस हाल पूछने के लिए।" },
    ar: { item: "ختم صوت مألوف", buff: "+70 للدفء، +∞ لما لن تندم عليه", flavor: "اتّصل بوالديك. بلا سبب، فقط لتطمئنّ عليهما." },
  },
];
